blank_issues_enabled: true
contact_links:
  - name: 功能请求
    url: https://github.com/Class-Widgets-Community/Class-Widgets-1-Community-Edition/discussions/categories/Feature
    about: 提出一项新的功能。
  - name: 讨论区
    url: https://github.com/Class-Widgets-Community/Class-Widgets-1-Community-Edition/discussions/
    about: 使用中若遇到问题或有新点子新需求，建议在这里求助和征求意见。
